### ISSUE TITLE
[core-css-reset] Add a means to keep the global footer at the bottom of the viewport

### ISSUE THREAD

**Issue by theetrain** [telus/tds-core#860]
## Description

Originally reported by @smm-telus 

When a TELUS page has content too short to fill the browser's height, the footer appears directly below the content, leaving white space between the footer and the bottom of the viewport.

## Recommendation

Provide a sass mixin to automatically resize the `<main>` DOM element, keeping the page footer at the bottom.

```scss
// core-css-reset/_mixins.scss
@mixin flex-main {
  html, body {
    height: 100%;
  }
  body {
    display: flex;
    flex-direction: column;
  }
  body > main {
    flex: 1 0 auto;
  }
}
```

## Usage

```scss
// app.scss
@import "~@tds/core-css-reset/mixins";

@include flex-main;
```

## Screenshots

Reproduced issue: when the content of a page is too short, the footer does not appear next to the bottom of the viewport (see below).

### Before 

![image](https://user-images.githubusercontent.com/12798751/49828374-b11a2f00-fd59-11e8-9744-f0208fbb6019.png)

### After

![image](https://user-images.githubusercontent.com/12798751/49891033-8ab8ca00-fe13-11e8-80bc-277e78b8ea49.png)

## Meta

- TDS version: v1.1.1
- Willing to develop solution: Yes
- Has workaround: Yes
- High impact: Yes
- Designer/Developer Pair: @smm-telus
